<a href="https://colab.research.google.com/github/hinda-mt/hinda-mt/blob/main/CH6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Write a Python program to convert an array to an ordinary list with the same items.

In [ ]:
import numpy as np 
arr = np.array([1,2,3]) # 1d array 
print(f'Numpy Array:\n{arr}') 

mlist = arr.tolist() # converting array to a list
print(f'List: \n{mlist}') 

Numpy Array:
[1 2 3]
List: 
[1, 2, 3]


2.Write a NumPy program to compute the sum of the diagonal element of a given array

**2D**
**n*n**



In [ ]:
 import numpy as np

n_arr = np.random.randint(0, 10, size=(3, 3, 2))

res_list = [int(n) for n in np.nditer(n_arr)]

res_list

[1, 2, 6, 7, 5, 8, 0, 3, 1, 3, 8, 0, 9, 8, 8, 2, 2, 9]

In [ ]:
 import numpy as np
n_arr = np.array([[1, 21, 30],
                 [63 ,434, 3],
                 [54, 54, 56]])

diag = np.diagonal(n_arr)
print (diag)
res=np.trace(n_arr) 
print(res)


[  1 434  56]
491


3.Given an array of your choice, get all the values higher than X

**X :if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2.**


In [ ]:
import numpy as np 
a= np.array([[1,2],[3,5]])
print(f'NumPy Array:\n{a}') 

x=int(input())
v= np.amax(a,axis=0) #rows
for i in  a :
    if (v>x).all(): 
      print(v,"are higher than",x)
#I NEED MORE explanation for this one cz i didn't get the perfect result

NumPy Array:
[[1 2]
 [3 5]]
2
[3 5] are higher than 2
[3 5] are higher than 2


In [ ]:
n_arr = np.random.randint(0, 20, size=(3, 3))
print(n_arr)


[[ 3  7  5]
 [ 5  6 12]
 [18 19 11]]


In [ ]:
cond = n_arr > 5 
n_arr[cond]

array([ 7,  6, 12, 18, 19, 11])

4.Given two arrays A&B having the same shape. 

**The task is to apply addition of A and B : C is the new array.**

In [ ]:
import numpy as np
A = np.array([[1,2],[3,5]]) 
B = np.array([[10,2],[6,5]]) 

newarr = np.add(A,B)
# OR C=A+B


print(f'sum Array:\n{C}')
#why np.sum(a,b) didn't get the same result ??? 
#DOES BUIlT IN FUNCTIONs for (lIST OR TUPlE) WON'T WORK FOR THE CASE OF ARRAY in numpy???

sum Array:
[[11  4]
 [ 9 10]]
